CREATE TABLE games(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  turn BIGINT,
  over BOOLEAN DEFAULT FALSE
);

CREATE TABLE boards(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  game_id BIGINT NOT NULL,
  winner BOOLEAN DEFAULT FALSE,
  CONSTRAINT games_id_fk
  FOREIGN KEY (game_id)
  REFERENCES games(id)
);

CREATE TABLE ships(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50),
  start INT NOT NULL,
  end INT NOT NULL,
  sunk BOOL DEFAULT FALSE,
  ship_board_id BIGINT NOT NULL,
  CONSTRAINT ship_boards_id_fk
  FOREIGN KEY (ship_board_id)
  REFERENCES boards(id)
);

CREATE TABLE moves(
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  point INT NOT NULL,
  status VARCHAR(4) DEFAULT 'MISS',
  move_board_id BIGINT NOT NULL,
  CONSTRAINT move_boards_id_fk
  FOREIGN KEY (move_board_id)
  REFERENCES boards(id)
)