platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/ukhomeofficedigital/mysql

inputs:
- name: bship

outputs:
- name: compiled-jar

run:
  path: ./bship/ci/test.sh