platform: linux

image_resource:
  type: docker-image
  source:
    repository: ryandur/mysql-openjdk8

params:
  MYSQL_DATABASE: bs
  MYSQL_ALLOW_EMPTY_PASSWORD: yes

inputs:
- name: bship_repo

run:
  path: ./bship/ci/test.sh