resources:
- name: bship
  type: git
  source:
    uri: https://github.com/RyanDur/bship.git
    branch: master

jobs:
- name: test
  plan:
  - get: bship
  - task: tests
    file: bship/ci/build.yml

