CREATE TABLE games(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE boards(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  game_id INT NOT NULL,
  CONSTRAINT games_id_fk
  FOREIGN KEY (game_id)
  REFERENCES games(id)
);

CREATE TABLE ships(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50),
  start INT NOT NULL,
  end INT NOT NULL,
  board_id INT NOT NULL,
  CONSTRAINT boards_id_fk
  FOREIGN KEY (board_id)
  REFERENCES boards(id)
);